In [39]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

In [79]:
data = load_breast_cancer()
X = data["data"]
y = data["target"]


In [83]:
import pandas as pd
df = pd.DataFrame(X,y)
print(df)

       0      1       2       3        4        5        6        7       8   \
0   17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010  0.14710  0.2419   
0   20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690  0.07017  0.1812   
0   19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740  0.12790  0.2069   
0   11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140  0.10520  0.2597   
0   20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800  0.10430  0.1809   
..    ...    ...     ...     ...      ...      ...      ...      ...     ...   
0   21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390  0.13890  0.1726   
0   20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400  0.09791  0.1752   
0   16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251  0.05302  0.1590   
0   20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140  0.15200  0.2397   
1    7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000  0.00000  0.1587   

         9   ...      20     21      22

In [87]:
X_tensor =  torch.from_numpy(X).float()
y_tensor = torch.from_numpy(y).float()
print(X_tensor)

tensor([[1.7990e+01, 1.0380e+01, 1.2280e+02,  ..., 2.6540e-01, 4.6010e-01,
         1.1890e-01],
        [2.0570e+01, 1.7770e+01, 1.3290e+02,  ..., 1.8600e-01, 2.7500e-01,
         8.9020e-02],
        [1.9690e+01, 2.1250e+01, 1.3000e+02,  ..., 2.4300e-01, 3.6130e-01,
         8.7580e-02],
        ...,
        [1.6600e+01, 2.8080e+01, 1.0830e+02,  ..., 1.4180e-01, 2.2180e-01,
         7.8200e-02],
        [2.0600e+01, 2.9330e+01, 1.4010e+02,  ..., 2.6500e-01, 4.0870e-01,
         1.2400e-01],
        [7.7600e+00, 2.4540e+01, 4.7920e+01,  ..., 0.0000e+00, 2.8710e-01,
         7.0390e-02]])


In [88]:
X_train,X_test,y_train,y_test = train_test_split(X_tensor,y_tensor,test_size=0.2,random_state=42)
print(f"Train data set is of size : {X_train.shape}")
print(f"Train data set is of size : {X_test.shape}")
print(X_test,y_test)

Train data set is of size : torch.Size([455, 30])
Train data set is of size : torch.Size([114, 30])
tensor([[1.2470e+01, 1.8600e+01, 8.1090e+01,  ..., 1.0150e-01, 3.0140e-01,
         8.7500e-02],
        [1.8940e+01, 2.1310e+01, 1.2360e+02,  ..., 1.7890e-01, 2.5510e-01,
         6.5890e-02],
        [1.5460e+01, 1.9480e+01, 1.0170e+02,  ..., 1.5140e-01, 2.8370e-01,
         8.0190e-02],
        ...,
        [1.1520e+01, 1.4930e+01, 7.3870e+01,  ..., 9.6080e-02, 2.6640e-01,
         7.8090e-02],
        [1.4220e+01, 2.7850e+01, 9.2550e+01,  ..., 8.2190e-02, 1.8900e-01,
         7.7960e-02],
        [2.0730e+01, 3.1120e+01, 1.3570e+02,  ..., 1.6590e-01, 2.8680e-01,
         8.2180e-02]]) tensor([1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1.,
        1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
        0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
        1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 

In [118]:
class CancerDetectionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer_1 = nn.Linear(in_features=30,out_features=100)
        self.layer_2 = nn.Linear(in_features=100,out_features=50)
        self.layer_3 = nn.Linear(in_features=50,out_features=1)
        self.relu  = nn.ReLU()
    def forward(self,x:torch.tensor):
        return self.layer_3(self.relu(self.layer_2(self.relu(self.layer_1(x)))))



In [119]:
model_0 = CancerDetectionModel()
model_0.state_dict()

OrderedDict([('layer_1.weight',
              tensor([[-0.1721, -0.1249, -0.0917,  ...,  0.1218,  0.0498, -0.0784],
                      [ 0.1288,  0.1171,  0.1571,  ..., -0.0786,  0.0444,  0.0440],
                      [ 0.1486,  0.1023,  0.0429,  ..., -0.1425,  0.0864, -0.0563],
                      ...,
                      [ 0.1066,  0.1098, -0.0088,  ..., -0.0159, -0.1708,  0.0928],
                      [ 0.0151,  0.0770, -0.0018,  ...,  0.0336, -0.1062, -0.1439],
                      [ 0.0849, -0.0785,  0.0684,  ..., -0.1378,  0.0272,  0.0528]])),
             ('layer_1.bias',
              tensor([ 0.0424,  0.1136,  0.1173, -0.1591,  0.0860,  0.1134, -0.0922, -0.1139,
                      -0.1640, -0.1801,  0.0954,  0.0519, -0.0992, -0.1632, -0.1697,  0.1657,
                       0.0601,  0.0298, -0.0151,  0.0745,  0.0198,  0.0788,  0.0466, -0.0941,
                      -0.0853,  0.0481,  0.0463,  0.1289, -0.1351,  0.0887, -0.1675,  0.0156,
                      -0.148

In [120]:
def accuracy_fn(y_true,y_pred):
    correct = torch.eq(y_true,y_pred).sum().item()
    acc = (correct/len(y_pred)) * 100
    return acc

In [121]:
optimizer = torch.optim.SGD(params=model_0.parameters(),lr=0.001)
loss_fn = nn.BCEWithLogitsLoss()

In [123]:
torch.manual_seed(42)
epochs = 1000
for epoch in range(epochs):
    model_0.train()
    y_logits = model_0.forward(X_train).squeeze()
    y_preds = torch.round(torch.sigmoid(y_logits)) 
    loss = loss_fn(y_logits,y_train)
    acc = accuracy_fn(y_train,y_preds)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    with torch.inference_mode():
        test_logits = model_0.forward(X_test).squeeze()
        test_preds = torch.round(torch.sigmoid(test_logits))

        test_loss = loss_fn(test_logits,y_test)
        test_acc = accuracy_fn(y_test,test_preds) 
    if(epoch % 100 == 0):
        print(f"Epoch : {epoch} | Train Loss : {loss:.5f}, Train Acc : {acc:.2f} % | Test Loss : {test_loss:.5f}, Test Acc : {test_acc:.2f} % ")


Epoch : 0 | Train Loss : 0.21180, Train Acc : 91.43 % | Test Loss : 0.13268, Test Acc : 95.61 % 
Epoch : 100 | Train Loss : 0.22062, Train Acc : 91.65 % | Test Loss : 0.13840, Test Acc : 93.86 % 
Epoch : 200 | Train Loss : 0.22730, Train Acc : 90.77 % | Test Loss : 0.14813, Test Acc : 92.11 % 
Epoch : 300 | Train Loss : 0.21399, Train Acc : 91.43 % | Test Loss : 0.13790, Test Acc : 93.86 % 
Epoch : 400 | Train Loss : 0.20189, Train Acc : 92.09 % | Test Loss : 0.12523, Test Acc : 95.61 % 
Epoch : 500 | Train Loss : 0.19807, Train Acc : 92.09 % | Test Loss : 0.12090, Test Acc : 95.61 % 
Epoch : 600 | Train Loss : 0.19588, Train Acc : 92.31 % | Test Loss : 0.11796, Test Acc : 95.61 % 
Epoch : 700 | Train Loss : 0.22258, Train Acc : 90.99 % | Test Loss : 0.14586, Test Acc : 92.11 % 
Epoch : 800 | Train Loss : 0.19602, Train Acc : 92.09 % | Test Loss : 0.12065, Test Acc : 94.74 % 
Epoch : 900 | Train Loss : 0.19141, Train Acc : 92.31 % | Test Loss : 0.11736, Test Acc : 95.61 % 


In [125]:
from pathlib import Path
MODEL_PATH = Path("D:\Computer Vision\Pytorch\models")
MODEL_PATH.mkdir(parents=True,exist_ok=True)
 
MODEL_NAME =  "Breast Cancer Classification.pth"
MODEL_SAVE_PATH =  MODEL_PATH/MODEL_NAME

print(f"Saving mode to : {MODEL_SAVE_PATH}")
torch.save(obj=model_0.state_dict(),f=MODEL_SAVE_PATH)

Saving mode to : D:\Computer Vision\Pytorch\models\Breast Cancer Classification.pth
